extends:
  - airbnb
  - plugin:import-order/recommended
env:
  browser: true
  webextensions: true
  jquery: true
parser: babel-eslint
plugins:
  - react
  - import-order
globals:
  _: true
  debug: true
  __ENV__: true
  __VENDOR__: true
  LIVERELOAD: true
rules:
  arrow-body-style: off
  no-console: off
  no-param-reassign: off
  no-use-before-define: off
  quotes:
    - error
    - double
