extends:
  - airbnb
  - plugin:import-order/recommended
env:
  browser: true
  webextensions: true
  jquery: true
parser: babel-eslint
plugins:
  - react
  - import-order
globals:
  debug: true
  __ENV__: true
  __VENDOR__: true
  LIVERELOAD: true
rules:
  arrow-body-style: off
  no-console: off
  no-param-reassign: off
  no-use-before-define: off
  no-else-return: off
  react/prefer-stateless-function: off
  quote-props:
    - error
    - consistent
  quotes:
    - error
    - double
  valid-jsdoc:
    - error
    - requireParamDescription: false
      requireReturnDescription: false
      requireReturn: false
      prefer:
        return: return
